/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#004ac6',
        'primary-container': '#2563eb',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'on-primary-container': '#eeefff',
        secondary: '#712ae2',
        'secondary-container': '#8a4cfc',
        'secondary-fixed': '#eaddff',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#25005a',
        'on-secondary-fixed-variant': '#5a00c6',
        'on-secondary-container': '#fffbff',
        tertiary: '#943700',
        'tertiary-container': '#bc4800',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb596',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7d2d00',
        'on-tertiary-container': '#ffede6',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f9f9ff',
        'on-background': '#121b2e',
        surface: '#f9f9ff',
        'on-surface': '#121b2e',
        'surface-variant': '#d9e2fc',
        'on-surface-variant': '#434655',
        'surface-dim': '#d1daf4',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'surface-container': '#e9edff',
        'surface-container-high': '#e1e8ff',
        'surface-container-highest': '#d9e2fc',
        'surface-panel': '#ffffff',
        'surface-tint': '#0053db',
        'inverse-surface': '#273044',
        'inverse-on-surface': '#edf0ff',
        'inverse-primary': '#b4c5ff',
        outline: '#737686',
        'outline-variant': '#c3c6d7',
        'bg-canvas': '#f5f7fb',
        'border-subtle': '#e6e9ef',
        'border-nested': '#eef0f4',
        'text-muted': '#7b8496',
        'sidebar-base': '#101827',
        'sidebar-hover': '#182235',
        'sidebar-pill': '#263247',
        'sidebar-text': '#cbd5e1',
        'sidebar-muted': '#718096',
        'status-success-bg': '#ecfdf3',
        'status-success-text': '#15803d',
        'status-success-dot': '#16a34a',
        'status-warning-bg': '#fff7ed',
        'status-warning-text': '#c2410c',
        'status-warning-dot': '#ea8a00',
        'status-info-bg': '#eff6ff',
        'status-info-text': '#1d4ed8',
        'status-danger-bg': '#fef2f2',
        'status-danger-text': '#b91c1c',
        'status-danger-dot': '#dc2626',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.875rem',
        'space-lg': '1rem',
        'space-xl': '1.25rem',
        gutter: '1rem',
        'gutter-desktop': '1rem',
        'gutter-mobile': '0.75rem',
        margin: '1.25rem',
        'margin-mobile': '0.75rem',
      },
      fontFamily: {
        'caption-medium': ['Inter'],
        'body-medium': ['Inter'],
        'display-stat': ['Inter'],
        'tag-counter': ['Inter'],
        'headline-lg': ['Inter'],
        'label-caps': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'title-md': ['Inter'],
        'metric-sub': ['Inter'],
        'subheading-sm': ['Inter'],
        'body-base': ['Inter'],
        'badge-micro': ['Inter'],
        'caption-sm': ['Inter'],
      },
      fontSize: {
        'caption-medium': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '600' }],
        'body-medium': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '600' }],
        'display-stat': ['26px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'tag-counter': ['10px', { lineHeight: '12px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-lg': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'headline-lg-mobile': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-md': ['16px', { lineHeight: '22px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'metric-sub': ['20px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'subheading-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'badge-micro': ['11px', { lineHeight: '14px', letterSpacing: '0em', fontWeight: '500' }],
        'caption-sm': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
